#JSpecView Application Properties
#Mon Jan 05 14:40:32 CST 2026
integralFactor=50
AtoTSeparateWindow=false
useDirectoryLastExportedFile=false
confirmBeforeExit=true
automaticallyIntegrate=false
automaticallyShowLegend=false
defaultDisplaySchemeName=Default
automaticTAConversion=false
showGrid=false
showStatusBar=true
integralPlotColor=\#ff0000
directoryLastOpenedFile=
useDirectoryLastOpenedFile=true
directoryLastExportedFile=
svgForInkscape=false
integralOffset=30
showXScale=true
showSidePanel=true
showToolBar=true
recentFilePaths=http\://SIMULATION/H1/tylenol, C\:\\Users\\hansonr\\Downloads\\nmrium-1h-predicted-download.jdx, C\:\\Users\\hansonr\\Downloads\\nmrium-13c-download.jdx, C\:\\Users\\hansonr\\Downloads\\new-h1-all-json$.jdx, C\:\\Users\\hansonr\\Downloads\\new-h1-all-json.jdx, C\:\\temp\\cache\\old1h\\old-jcamp, C\:\\temp\\cache\\new1h\\new-jcamp, http\://SIMULATION/C13/tylenol, C\:\\temp\\cache\\old13c\\old-jcamp, C\:\\Users\\hansonr\\Downloads\\2.zip..2_13C.zip
automaticallyOverlay=false
showCoordinates=false
integralMinY=0.1
showYScale=true
