#JSpecView Application Properties
#Fri Feb 20 18:05:18 CST 2026
integralFactor=50
AtoTSeparateWindow=false
useDirectoryLastExportedFile=false
confirmBeforeExit=true
automaticallyIntegrate=false
automaticallyShowLegend=false
defaultDisplaySchemeName=Default
automaticTAConversion=false
showGrid=false
showStatusBar=true
integralPlotColor=\#ff0000
directoryLastOpenedFile=C\:\\temp
useDirectoryLastOpenedFile=true
directoryLastExportedFile=
svgForInkscape=false
integralOffset=30
showXScale=true
showSidePanel=true
showToolBar=true
recentFilePaths=C\:\\temp\\mnova\\test\\test-predict.jdx, C\:\\temp\\jdx\\nmr_assigned.jdx, c\:\\temp\\t.jdx, c\:\\temp\\tb.jdx, http\://SIMULATION/H1/tylenol, http\://SIMULATION/C13/tylenol, C\:\\temp\\t.jdx, C\:\\Users\\hansonr\\Downloads\\nmrium-1h-predicted-download.jdx, C\:\\Users\\hansonr\\Downloads\\nmrium-13c-download.jdx, C\:\\Users\\hansonr\\Downloads\\new-h1-all-json$.jdx
automaticallyOverlay=false
showCoordinates=false
integralMinY=0.1
showYScale=true
