Jmol.___JmolDate="$Date: 2026-02-12 13:53:41 -0600 (Thu, 12 Feb 2026) $"
Jmol.___fullJmolProperties="src/org/jmol/viewer/Jmol.properties"
Jmol.___JmolVersion="16.3.51" // (legacy) also 16.3.52 (swingJS) 
